name: Go

on:
  push:

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
    
    - name: Start Minikube
      run: |
        sudo minikube start --kubernetes-version=v1.24.10 --force

    - name: Wait for Minikube
      run: |
        while [ "$(sudo minikube status --format '{{.Host}}')" != "Running" ]; do
          echo "Waiting for Minikube to start..."
          sleep 5
        done

    - name: Install Rhino Operator
      run: |
        sudo kubectl apply -f https://raw.githubusercontent.com/OpenRHINO/RHINO-Operator/main/install-rhino-operator.yaml
        echo "Waiting for RHINO Operator to start..."
        sleep 30

    - name: Build
      run: sudo make build

    - name: Configure Docker to use Minikube's Docker daemon
      run: |
        sudo minikube -p minikube docker-env | sudo tee /tmp/docker-env.sh
        sudo chmod +x /tmp/docker-env.sh

    - name: Test
      run: |
        sudo --preserve-env=GOROOT,GOPATH,DOCKER_TLS_VERIFY,DOCKER_HOST,DOCKER_CERT_PATH,MINIKUBE_ACTIVE_DOCKERD bash -c "source /tmp/docker-env.sh && go test -v ./..."


